### ISSUE TITLE
monitor for pool solvency issues

### ISSUE THREAD

**Issue by hackjealousy** [block42-blockchain-company/thornode-telegram-bot#109]
from Leena (@leena56):

"Ideally the thornode bot cc Paul monitors for pool solvency issues, and alerts everyone everytime there is a solvency issue change. The bot should then monitor the queue and identify if a backlog is ocurring. Any community member can "fix" any issues by donating in the assets to the system to allow it to recover."

**Comment by thorchain-admin** [comment]
The process should be:

1) Pull the current Asgard and yggdrasil vault addresses from the system. 
http://18.159.173.48:1317/thorchain/vaults/yggdrasil <- ygg balance && addresses
http://18.159.173.48:1317/thorchain/vaults/asgard <- asgard balances
http://18.159.173.48:1317/thorchain/pool_addresses <- Asgard address

2) Query for the respective on-chain addresses
https://dex.binance.org/api/v1/account/bnb1ysh9qt0l70jjac0jjvat7rdlv2752sws0x34qr

3) Compare the two. Any time solvency changes, send an alert. 

4) Monitor the queue and send an alert anytime the queue starts growing.
http://18.159.173.48:1317/thorchain/queue

**Comment by rekt0x** [comment]
Is this done now @mr-rooftop?
