### ISSUE TITLE
Update Node Configuration Parameters

### ISSUE THREAD

**Issue by rekt0x** [block42-blockchain-company/thornode-telegram-bot#121]
![image](https://user-images.githubusercontent.com/6087393/97410893-e7d2a180-18ff-11eb-8d01-67664309e160.png)

See here: https://github.com/block42-blockchain-company/thornode-telegram-bot#bitcoin

The parameters are required using a weird pattern, use a common pattern like:

`USERNAME:PASSWORD@IP_ADDRESS:PORT`

so e.g.:

`BITCOIN_NODE_IPS=user1:password2@1.2.3.4:1337,user2:password2@5.6.7.8:1337`

⚠️ The other nodes (Binance and Ethereum) do not require username and password, but also use the same pattern for them so one can specify IP address and port, e.g.: `ETHEREUM_NODE_IPS=IP_ADDRESS:PORT`

**Comment by mbartn** [comment]
Bitcoin configuration will be solved by #128, other nodes not yet

**Comment by mbartn** [comment]
pattern for all other nodes fixed
