### ISSUE TITLE
Join in, churn out notifications

### ISSUE THREAD

**Issue by rekt0x** [block42-blockchain-company/thornode-telegram-bot#19]
Send notifications based on when the validator node (which was previously in standby mode) joins in and becomes an active validator.

Send another notification when the validator node gets churned out.

@cbarraford How can we check if a node becomes an active validator, which has in standby before? How can we check if a node got churned out?

**Comment by cbarraford** [comment]
i would say, anytime the status changes to whatever it changes to, notify. The status is available in the `/nodeaccounts` or `/nodeaccount/<address>`

**Comment by rekt0x** [comment]
Alright, we are already doing that. Closing this one.
