### ISSUE TITLE
Be able to subscribe to all nodes for notifications (US 2 - Sprint Week 16/17)

### ISSUE THREAD

**Issue by cbarraford** [block42-blockchain-company/thornode-telegram-bot#2]
Instead of adding just one node, be good to add all nodes

**Comment by mr-rooftop** [comment]
Guess the description should be neglected in preference of the title.

As the goal for the bot is to be useful for node operaters to monitor their own nodes, it would not make sense to monitor *all* thornodes but being able to add multiple addresses right?

**Comment by cbarraford** [comment]
at least multiple addresses. Unless people want to run a bot per node.

**Comment by rekt0x** [comment]
I guess with multiple addresses we should be good for now. I'm not really seeing the usecase to subscribe to *all* nodes (also those that are not mine). I think a separate feature would be more interesting in that case to monitor the overall network (e.g. # of thornodes, total bonded rune, etc.) and if you want you can get notifications or e.g. daily digests based on that.

**Comment by cbarraford** [comment]
All nodes is helpful for chain analytics. People who want to watch overall performance and collect metrics about chain behavior

**Comment by rekt0x** [comment]
Ok, makes sense if you want to watch the whole network.
