### ISSUE TITLE
Add # of unconfirmed txs to node stats

### ISSUE THREAD

**Issue by rekt0x** [block42-blockchain-company/thornode-telegram-bot#21]
When querying the stats of a certain thornode add the number of unconfirmed transactions to the bot's message.

docs:
https://docs.tendermint.com/master/rpc/#/Info/num_unconfirmed_txs

e.g.: http://67.205.166.241:26657/num_unconfirmed_txs

**Comment by mr-rooftop** [comment]
What is the motivation behind this feature?
Why does the node operator want to know about this?

**Comment by mr-rooftop** [comment]
if this is the return value:
```
{
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "n_txs": "31",
    "total": "82",
    "total_bytes": "19974"
  }
}
```

what is the number we want to see? `n_txs` or `total`?

**Comment by rekt0x** [comment]
@cbarraford

**Comment by cbarraford** [comment]
i think you want total, https://github.com/tendermint/tendermint/blob/master/rpc/core/mempool.go#L140
