### ISSUE TITLE
ADD: Show all available  Node Accounts

### ISSUE THREAD

**Issue by thorchain-admin** [block42-blockchain-company/thornode-telegram-bot#26]
Add a button to "Show All Nodes" that lists all nodes alongside:

* address
* bond
* status
* slashpoints
* version
* status_since

http://34.237.137.77:1317/thorchain/nodeaccounts

**Comment by mr-rooftop** [comment]
You mean a Button that shows all monitored information of all added ThorNode addresses with one click?

Currently we monitor
- address
- bond 
- status
- slashpoints

If we add 
- version
- status_since
to "Show all Nodes", we should also show this information in "Show THORNode Stats".

Do you want to add these two attributes in both ?

**Comment by rekt0x** [comment]
I think this is not about monitoring all nodes, but just showing the details for all nodes on the network. Just a one-time thing when you click the button.

**Comment by mr-rooftop** [comment]
Exactly. "Show THORNode Stats" is also not about monitoring

**Comment by rekt0x** [comment]
Maybe introduce this function within a "Network" sub menu or so. We can also put in some overall network stats in the future (e.g. # of nodes, amount of bonded RUNE, etc.)
