### ISSUE TITLE
/health endpoint (US 3 - Sprint Week 16/17)

### ISSUE THREAD

**Issue by cbarraford** [block42-blockchain-company/thornode-telegram-bot#3]
Create an http endpoint that just returns a 200 response. This is a healthcheck endpoint to ensure the monitoring service is up itself. People can use external monitoring services to monitor this.

**Comment by mr-rooftop** [comment]
Got it.
Should we bake the healthcheck into the Dockerfile?

**Comment by cbarraford** [comment]
I was imaging just open a HTTP port in the code (ie flask). But whatever works

**Comment by rekt0x** [comment]
Is it necessary to be able to do health checks for the bot from outside? (e.g. using https://updown.io) Docker itself can do health checks and restart containers if they are faulty or unhealthy. But then you wouldn't be able to check that externally.

If yes, just opening a port using Flask sounds good.

**Comment by cbarraford** [comment]
thats good, we should add that docker healthcheck. But what if docker dies?

**Comment by rekt0x** [comment]
i think in that case you get notified by your uptime monitoring service because your node/server does not respond any more to health checks.

**Comment by mr-rooftop** [comment]
Hey @cbarraford !
Just wanted to confirm that you're ok with having a health check baked directly into docker, without an external port being open.

**Comment by cbarraford** [comment]
That would check that docker is running, not the telegram bot process, you know? Is there a way to check a docker container is running?

**Comment by mr-rooftop** [comment]
This health check makes sure that the telegram bot container is running correctly. If it doesn't, the thornode bot container gets restarted. So the inbuilt solution assures that the container is running.

Is that good for you?


If your question meant to check whether the actual docker engine is running, one could do a check on his unix system with 
```pgrep -f docker```
And then pipe it together with a command to restart docker e.g.:
```
pgrep -f docker > /dev/null || systemctl start docker
```

**Comment by cbarraford** [comment]
whats important is that the docker container running the bot is running. Anyway you want to ensure that is good. Checking the daemon itself prob isn't a great proxy, but better than nothing

**Comment by mr-rooftop** [comment]
Yes checking the docker daemon itself isn't our goal.
Ok great thx for the clarification, then we got this health check straight :small_airplane:
