### ISSUE TITLE
ADD: Emoji for Node Status

### ISSUE THREAD

**Issue by thorchain-admin** [block42-blockchain-company/thornode-telegram-bot#38]
Show Node Status as Emoji on Node List:

<img width="396" alt="image" src="https://user-images.githubusercontent.com/41812729/81559693-397b8400-93d3-11ea-9ecb-3bfb2610776e.png">

`💚 thorxxxx` <- active
`🗓 thorxxx` <- standby
`🛑 thorxxx` <- deactive

**Comment by mr-rooftop** [comment]
Are active, standby, deactive the only three statuses that can occur?
