### ISSUE TITLE
Custom ip address

### ISSUE THREAD

**Issue by cbarraford** [block42-blockchain-company/thornode-telegram-bot#4]
Its good to leave the default to `localhost` but it would be good to add a cli flag to add an IP address and monitor a remote system.

**Comment by mr-rooftop** [comment]
Until now localhost isn't actually used for the monitoring. One ip is randomly chosen from https://testnet-seed.thorchain.info and its endpoint /thorchain/nodeaccounts is accessed. 

Shouldn't first be a github issue openend and solved like "Monitor local thornode stats with localhost"?

**Comment by cbarraford** [comment]
its possible thorchain API won't be publicly available, only midgard needs to be. So we can't assume that all random IPs in testnet are ok to hit. But I assume 99% of the time, people will hit localhost. The custom IP address is just to give another option.
