### ISSUE TITLE
Truncate node addresses

### ISSUE THREAD

**Issue by rekt0x** [block42-blockchain-company/thornode-telegram-bot#40]
![image](https://user-images.githubusercontent.com/6087393/81561035-d23ddf80-9392-11ea-92f2-3b18d2be3741.png)

Instead of showing the full address of each thornode `thor155fhk3zl2utx7msaynp5ag6epxpmjkrp7ytmr8` truncate the middle, e.g. like that: `thor155fh...ytmr8`

Then the buttons are not that big.

**Comment by mr-rooftop** [comment]
The buttons are as big as the Message above it.

But we could truncate it, cut the size of the buttons in half, and display them in pairs:
thorXX...XXX - thorXX...XXX
thorXX...XXX - thorXX...XXX
Add NODE   -  << BACK

**Comment by rekt0x** [comment]
Sounds good to put them in 2 columns beside each other.
