### ISSUE TITLE
Monitor chain heights (US 1 - Sprint Week 16/17)

### ISSUE THREAD

**Issue by cbarraford** [block42-blockchain-company/thornode-telegram-bot#5]
We want to monitor that chain heights are increasing. This would be thorchain, binance, bitcoin, etc. So we'll need IP addresses for each chain. These chains may run on a  separate IP address.

For thorchain/binance, its the same...
```
curl -s localhost:26657/status | jq -r '.result.sync_info.latest_block_height'
```

Bitcoin and ethereum we can handle a different day when we're further in the development

**Comment by mr-rooftop** [comment]
Must admit that I'm not too familiar with the THORchain skeleton after a quick look at the white paper.

Until now, only stats of thorchain nodes are monitored through the /nodeaccounts endpoint.
To do that, the user adds one (or in future more) thornode address.

Do I understand correctly that the chain height monitoring would mean to monitor different nodes than the now monitored thornodes?
So this doesn't relate at all to the above added thornode address? Can this be seen as a completely new feature, different from the monitoring until now?

Is it also necessary to add addresses for binance, bitcoin etc. nodes?
Should hardcoded or random addresses be used?

**Comment by cbarraford** [comment]
Chain height monitoring is a sanity check that YOUR node is healthy, and pulling down new blocks. And you're not comparing against other nodes, just that your own node has increasing block heights (ie not stuck on height 345). 

We'll want to do the same for each of the full nodes as well, which would be a different endpoint. This notifies the owner that one of their chains are broken, and will likely cause slash points
