### ISSUE TITLE
Display accrued bond rewards

### ISSUE THREAD

**Issue by mr-rooftop** [block42-blockchain-company/thornode-telegram-bot#56]
@sickmullahh on telegram gave us this idea:
"i want to be able to see how much rewards the node has accrued."

Display on Node details the accrued bond rewards of my (any?) node.

**Comment by thorchain-admin** [comment]
This will soon be available on the latest node account endpoint. 

https://gitlab.com/thorchain/thornode/-/merge_requests/1153
