### ISSUE TITLE
Vault key verification

### ISSUE THREAD

**Issue by mr-rooftop** [block42-blockchain-company/thornode-telegram-bot#58]
@hackjealousy gave us this idea on telegram:
"vault key verification (ask all the nodes and make sure they agree) would actually be very nice."

We need to discuss how this could be achieved.

**Comment by rekt0x** [comment]
Probably just query `http://{NODE_IP}:8080/v1/thorchain/pool_addresses` from a set of `n` random nodes in the network and use the majority response as truth.

**Comment by mr-rooftop** [comment]
Good process.
But how do we get those Node IPs?

**Comment by rekt0x** [comment]
`http://{NODE_IP}:1317/thorchain/nodeaccounts` returns the info of all nodes including the `ip_address`.

So you could go in using the seed node(s) via `https://testnet-seed.thorchain.info`, then discover all nodes in the network via `http://{SEED_NODE_IP}:1317/thorchain/nodeaccounts` and use a subset `n` of them to get the "correct" vault addresses.

**Comment by hackjealousy** [comment]
> and use a subset n of them to get the "correct" vault addresses via http://{NODE_IP}:8080/v1/thorchain/pool_addresses.

I'd like to know the "correct" address as well as any disagreement -- the fact that nodes on the network are advertising the wrong vault address would be indicative of an active attack.

**Comment by rekt0x** [comment]
Then maybe show the vault addresses like this:

Binance Chain
bnb123...789 (x nodes)
bnbabc...xyz (y nodes)

Bitcoin
...

Ethereum
...

Show all vault addresses with the count of how many nodes responded with it.
