### ISSUE TITLE
Active days up

### ISSUE THREAD

**Issue by BeliyDym** [block42-blockchain-company/thornode-telegram-bot#65]
If possible would be nice to see information about "active" days up since churned in

**Comment by mr-rooftop** [comment]
Thanks for this idea!

Please help me out:
Is there any way to see the timestamp when a node churned in?

**Comment by BeliyDym** [comment]
I believe it is shown as "Status Since". 
I think it is since "block", so you would need to see the "current block" minus "since block", multiple by block time and divide by /minutes/hours/days...
.....
Status | active
-- | --
Status Since | 32403
.....
