### ISSUE TITLE
Admin tasks

### ISSUE THREAD

**Issue by cbarraford** [block42-blockchain-company/thornode-telegram-bot#7]
Add the ability for a telegram authorized user to do admin tasks on the box. Like restart docker or the server. More thought has to be put in to figure out a secure way of doing this

**Comment by mr-rooftop** [comment]
It's possible to restrict access to certain functions of the bot via user_id whitelisting.

**Comment by rekt0x** [comment]
Great idea @mr-rooftop In addition to that access is also limited because of the Telegram bot token (only the owner of the nodes should be in possession of it).

**Comment by mr-rooftop** [comment]
@cbarraford I wanted to ask which admin tasks you have in mind now?
Restarting the host of the docker container is heavily dependent on the host system on the container too. Same with restarting docker.
I guess restarting any hosts is a lot of work compared to the features so far.

**Comment by rekt0x** [comment]
Just came around this thread: https://stackoverflow.com/questions/39468841/is-it-possible-to-start-a-stopped-container-from-another-container
So the thornode will run as a docker container and let's assume all other nodes (binance chain, ethereum, bitcoin, ...) are also running as docker containers, then we can pass the docker socket to the thornode bot container, install docker inside the thornode bot container which then enables us to control docker from telegram (start, stop, restart, probably also logs, etc.).

So it's possible and the solution is pretty nice but the question is if we want that due to security concerns.

What do you think @cbarraford?

**Comment by cbarraford** [comment]
I would say as long as we specify a specific telegram user (securely) that has the rights to do so (ie, no user-specified, nobody can use admin tasks) its ok.

**Comment by cbarraford** [comment]
For those who are more security focused, they wouldn't even run this on the same box as thornode. They'd run it somewhere else and have it connect remotely. Then you don't have some mystery daemon running on the same box that has funds on it

**Comment by rekt0x** [comment]
Good point. Then we should add something like the telegram user id to the config file to enable this admin feature and only this user id can manage stuff. @mr-rooftop

**Comment by mr-rooftop** [comment]
For the first Admin Task Version I propose:

- Make sure only the owner of the Bot can perform admin tasks

- Admin can restart Telegram Bot Container

- Admin can restart Thornode Container

Good?

**Comment by rekt0x** [comment]
Sounds good to me @mr-rooftop

**Comment by cbarraford** [comment]
There isn't a "thornode" container. Its actually a series of containers. The container names are `thor-daemon`, `thor-api`, `bifrost`, `midgard`, and `timescale-db`

**Comment by mr-rooftop** [comment]
Thanks for the clarification.
We could make that the Telegram user has to write the name of the docker container he wants to restart. That way, we stay very flexible in the future no matter which container should be restarted.
@cbarraford ?

**Comment by cbarraford** [comment]
don't assume they know. I'd say give them a list of docker containers, and ask which one they'd like to restart, or "restart all"

**Comment by cbarraford** [comment]
and include the status with that list of containers (effectively giving them the result of `docker ps`)
